import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import StoreProvider from '@/components/providers/StoreProvider';
import { Toaster } from '@/components/ui/toaster';
import FirstLoading from '@/components/FirstLoading';
import { getCookie } from 'cookies-next';
import ReactQueryProvider from '@/components/providers/ReactQueryProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <StoreProvider>
            <FirstLoading>{children}</FirstLoading>
          </StoreProvider>
        </ReactQueryProvider>
        <Toaster />
      </body>
    </html>
  );
}
